#!/bin/bash

TAGS=$(wget -q -O- https://hub.docker.com/v2/repositories/library/node/tags | jq -r '.results[].name')


for tag in $TAGS;do
    mkdir -p "docker/$tag"
    cat << EOF > "docker/$tag/Dockerfile"
FROM node:$tag

USER node
EOF

    mkdir -p "docker/$tag-builder"
    cat << EOF > "docker/$tag-builder/Dockerfile"
FROM node:$tag

RUN apk update && apk add --no-cache \
    autoconf \
    automake \
    gcc \
    git \
    g++ \
    make \
    nasm \
    libtool \
    linux-headers \
    openssh \
    python \
    python-dev \
    zlib-dev
RUN npm i -g lerna
USER node
EOF

done