FROM node:lts-stretch

RUN apk update && apk add --no-cache     autoconf     automake     gcc     git     g++     make     nasm     libtool     linux-headers     openssh     python     python-dev     zlib-dev
RUN npm i -g lerna
USER node
