FROM node:lts-alpine3.9

RUN apk update && apk add --no-cache     autoconf     automake     gcc     git     g++     make     nasm     libtool     linux-headers     openssh     python     python-dev     zlib-dev

USER node
